### ISSUE TITLE
Improve the error message and logic when Dropbox's Permissions are incorrect

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/Airlift#40]
@arjunprakash027 

Looks like dropbox client / code is broken

```
WARNING: The folder Marker Data already exists.
ERROR: Error at division
Traceback (most recent call last):
  File "urllib3/util/ssl_.py", line 447, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airlift/dropbox_client.py", line 41, in __init__
  File "dropbox/base.py", line 1207, in files_create_folder
  File "dropbox/dropbox_client.py", line 304, in request
  File "dropbox/dropbox_client.py", line 372, in check_and_refresh_access_token
  File "dropbox/dropbox_client.py", line 405, in refresh_access_token
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airlift/cli.py", line 38, in cli
  File "airlift/dropbox_client.py", line 45, in __init__
airlift.utils_exceptions.CriticalError: ('Error during Dropbox client creation', SSLError(MaxRetryError("HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))")))
```

**Comment by IAmVigneswaran** [comment]
@arjunprakash027 

We can add something like `Dropbox API Permissions Error. Check your scopes in the Permissions tab under Dropbox's App Console.`

**Comment by IAmVigneswaran** [comment]
I will be close this issue as we have identified the issue.
