### ISSUE TITLE
After dependencies updates, Dropbox's Refresh Token Code and Client is Broken.

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/Airlift#41]
@arjunprakash027 

I believe I have further identified the issue. It seems after dependencies update, our dropbox's refresh token code and client is broken.

You can check this test build. 

https://github.com/TheAcharya/Airlift/actions/runs/11760883767

**Comment by IAmVigneswaran** [comment]
@arjunprakash027 

Base on our initial investigation, I believe it has to do with the latest version 2.2.3 of urllib3.

https://github.com/urllib3/urllib3/releases

**Comment by IAmVigneswaran** [comment]
@arjunprakash027 

Interestingly, I made a quick test with this this [test-build](https://github.com/TheAcharya/Airlift/actions/runs/11766083208). 

I get this error when trying to get dropbox refresh token.

```
WARNING: error during retreival of refresh token
Error during retreival of token! Do you want to try again? (y/n)
```

<hr>

Even after reverting to the previous  version of  urllib3, I am getting this error when trying to upload.

```
2024-11-10 23:02:25,081 [INFO    ] Airlift version 1.1.4
2024-11-10 23:02:25,082 [INFO    ] Created a Dropbox Client
2024-11-10 23:02:25,109 [WARNING ] The folder Marker Data already exists.
2024-11-10 23:02:25,113 [ERROR   ] Error at division
Traceback (most recent call last):
  File "urllib3/util/ssl_.py", line 440, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 793, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1099, in _validate_conn
  File "urllib3/connection.py", line 653, in connect
  File "urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 442, in ssl_wrap_socket
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 847, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airlift/dropbox_client.py", line 41, in __init__
  File "dropbox/base.py", line 1207, in files_create_folder
  File "dropbox/dropbox_client.py", line 304, in request
  File "dropbox/dropbox_client.py", line 372, in check_and_refresh_access_token
  File "dropbox/dropbox_client.py", line 405, in refresh_access_token
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airlift/cli.py", line 38, in cli
  File "airlift/dropbox_client.py", line 45, in __init__
airlift.utils_exceptions.CriticalError: ('Error during Dropbox client creation', SSLError(MaxRetryError("HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))")))

```

<hr>

Strangely, when I revert back to our [current release 1.1.3](https://github.com/TheAcharya/Airlift/releases/tag/v1.1.3)'s complied binary, I am able to create dropbox refresh token and upload data set without issue.

**Comment by arjunprakash027** [comment]
New update, it has nothing to do with urllib. It seems to be some kind of environment problem (or image problem) of servers that are spawned by github actions to build the binary

**Comment by IAmVigneswaran** [comment]
> New update, it has nothing to do with urllib. It seems to be some kind of environment problem (or image problem) of servers that are spawned by github actions to build the binary

Interesting! 

@arjunprakash027 Using this fresh [test build](https://github.com/TheAcharya/Airlift/actions/runs/11768786663), I am able to create dropbox refresh token and upload data set without issue.

**Comment by IAmVigneswaran** [comment]
@arjunprakash027 I have created a new branch https://github.com/TheAcharya/Airlift/tree/codebase-refactor-for-dependencies
